# Generated by Django 4.1.6 on 2023-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='createdYear',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='user',
            field=models.CharField(default='user', max_length=120),
        ),
    ]
