# Generated by Django 4.1.6 on 2023-02-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_scenario_createdyear_scenario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='createdYear',
            field=models.DateTimeField(verbose_name=2023),
        ),
    ]
