# Generated by Django 4.1.6 on 2023-02-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_alter_scenario_createdyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='createdYear',
            field=models.CharField(default='2023', max_length=10),
        ),
    ]
