# Generated by Django 4.1.6 on 2023-02-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0006_alter_scenario_createdyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='title',
            new_name='scenarioName',
        ),
    ]
