# Generated by Django 4.1.6 on 2023-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0007_rename_title_scenario_scenarioname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='createdYear',
            field=models.CharField(default='2023', max_length=120),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
