# Generated by Django 4.1.6 on 2023-02-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0008_alter_scenario_createdyear_alter_scenario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='user',
            new_name='lastModified',
        ),
    ]
